# Generated by Django 5.1.1 on 2024-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
