# Generated by Django 5.1.1 on 2024-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_statement_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
