# Generated by Django 5.1 on 2024-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraping_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.TextField(blank=True, null=True)),
                ('company_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('company_headquarters', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.CharField(blank=True, max_length=150, null=True)),
                ('regular_company_url', models.TextField(blank=True, null=True)),
                ('vmid', models.CharField(blank=True, max_length=100, null=True)),
                ('company_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_specialties', models.TextField(blank=True, null=True)),
                ('company_employee_count', models.CharField(blank=True, max_length=50, null=True)),
                ('company_employee_range', models.CharField(blank=True, max_length=50, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company_linkedin_id_url', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_profile_picture', models.TextField(blank=True, null=True)),
                ('company_year_founded', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_navigator_company_url', models.TextField(blank=True, null=True)),
                ('is_hiring', models.BooleanField(default=False)),
                ('specialties', models.CharField(blank=True, max_length=50, null=True)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_revenue_min', models.CharField(blank=True, max_length=50, null=True)),
                ('company_revenue_max', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('geographicArea', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraping_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('connections', models.CharField(blank=True, max_length=50, null=True)),
                ('years_in_position', models.CharField(blank=True, max_length=50, null=True)),
                ('months_in_position', models.CharField(blank=True, max_length=50, null=True)),
                ('years_in_company', models.CharField(blank=True, max_length=50, null=True)),
                ('months_in_company', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_navigator_url', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('current_positions', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('connection_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('heading', models.CharField(max_length=150)),
                ('scraping_type', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_url', models.TextField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('session_cookie', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('remove_duplicate_profiles', models.BooleanField(blank=True, default=False, null=True)),
                ('input_type', models.CharField(blank=True, max_length=50, null=True)),
                ('slots', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('scraping_id', models.CharField(blank=True, max_length=15, null=True)),
                ('scraping_name', models.CharField(blank=True, default='Untitled Sales Navigator Search Export', max_length=255, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('starting_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('launch', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_profiles', models.IntegerField(blank=True, null=True)),
                ('number_of_results_per_search', models.IntegerField(blank=True, null=True)),
                ('number_of_lines_per_launch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['starting_time'], name='scraping_sc_startin_184fd2_idx'), models.Index(fields=['status'], name='scraping_sc_status_a25b67_idx')],
            },
        ),
    ]
