# Generated by Django 5.1.1 on 2024-10-07 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Need To Plan', max_length=50)),
                ('monthly_or_annually', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annually'), ('14_days', '14 Days')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='inactive', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('execution_time_hours', models.DurationField(default=datetime.timedelta(0))),
                ('ai_credits_per_month', models.IntegerField(default=0)),
                ('used_credit', models.IntegerField(default=0)),
                ('scraping_slots', models.IntegerField(default=0)),
                ('used_slots', models.IntegerField(default=0)),
                ('unlimited_export', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('credits_rollover', models.BooleanField(default=False)),
                ('find_email_credits', models.IntegerField(default=0)),
                ('direct_number_credits', models.IntegerField(default=0)),
                ('mobile_number_credits', models.IntegerField(default=0)),
                ('lead_location_phone_number_credits', models.IntegerField(default=0)),
                ('lead_location_address_credits', models.IntegerField(default=0)),
                ('company_hq_number_credits', models.IntegerField(default=0)),
                ('company_hq_address_credits', models.IntegerField(default=0)),
                ('company_revenue_credits', models.IntegerField(default=0)),
                ('basic_filters', models.BooleanField(default=False)),
                ('advanced_filters', models.BooleanField(default=False)),
                ('export_leads_limit', models.IntegerField(default=0)),
                ('export_accounts_limit', models.IntegerField(default=0)),
                ('clean_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('team', 'Team')], max_length=50, unique=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('execution_time_hours', models.DurationField()),
                ('ai_credits_per_month', models.IntegerField()),
                ('scraping_slots', models.IntegerField()),
                ('unlimited_export', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('credits_rollover', models.BooleanField(default=True)),
                ('find_email_credits', models.IntegerField()),
                ('direct_number_credits', models.IntegerField()),
                ('mobile_number_credits', models.IntegerField()),
                ('lead_location_phone_number_credits', models.IntegerField()),
                ('lead_location_address_credits', models.IntegerField()),
                ('company_hq_number_credits', models.IntegerField()),
                ('company_hq_address_credits', models.IntegerField()),
                ('company_revenue_credits', models.IntegerField()),
                ('basic_filters', models.BooleanField(default=True)),
                ('advanced_filters', models.BooleanField(default=False)),
                ('export_leads_limit', models.IntegerField()),
                ('export_accounts_limit', models.IntegerField()),
                ('clean_data', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=100)),
                ('billing', models.CharField(blank=True, max_length=100)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('monthly_or_annually', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
